/************************************************************************************
 * 
 * V.1 기본 테이블 스크립트
 * - BBS_ITEM 게시판
 * 
 ************************************************************************************/

CREATE TABLE BBS_ITEM (
	ITEM_ID NUMBER NOT NULL,
	TITLE VARCHAR2(255) NOT NULL,
	USER_ID NUMBER NOT NULL,
	USER_NAME VARCHAR2(255) NOT NULL,
	MAP_ID NUMBER NOT NULL,
	LEVEL1 NUMBER,
	LEVEL2 NUMBER,
	LEVEL3 NUMBER,
	LEVEL4 NUMBER,
	CONTENT CLOB,
	RGST_DATE DATE DEFAULT SYSDATE,
	LAST_UPDT DATE DEFAULT SYSDATE,
	STATUS NUMBER NOT NULL,
	OPN_CNT NUMBER DEFAULT 0,
	RCMD_CNT NUMBER DEFAULT 0,
	READ_CNT NUMBER DEFAULT 0,
	CSTM_FIELD1 VARCHAR2(255),
	CSTM_FIELD2 VARCHAR2(255),
	CSTM_FIELD3 NUMBER,
	CSTM_DATE1 DATE,
	CSTM_DATE2 DATE
)TABLESPACE TB_DAT;

COMMENT ON TABLE BBS_ITEM IS '게시판 테이블';
COMMENT ON COLUMN BBS_ITEM.ITEM_ID  IS '일련번호';
COMMENT ON COLUMN BBS_ITEM.TITLE  IS '제목';
COMMENT ON COLUMN BBS_ITEM.USER_ID  IS '사용자번호';
COMMENT ON COLUMN BBS_ITEM.USER_NAME  IS '사용자이름';
COMMENT ON COLUMN BBS_ITEM.MAP_ID  IS '맵일련번호';
COMMENT ON COLUMN BBS_ITEM.LEVEL1  IS '레벨1';
COMMENT ON COLUMN BBS_ITEM.LEVEL2  IS '레벨2';
COMMENT ON COLUMN BBS_ITEM.LEVEL3  IS '레벨3';
COMMENT ON COLUMN BBS_ITEM.LEVEL4  IS '레벨4';
COMMENT ON COLUMN BBS_ITEM.CONTENT  IS '내용';
COMMENT ON COLUMN BBS_ITEM.RGST_DATE  IS '등록일자';
COMMENT ON COLUMN BBS_ITEM.LAST_UPDT  IS '수정일자';
COMMENT ON COLUMN BBS_ITEM.STATUS  IS '상태';
COMMENT ON COLUMN BBS_ITEM.OPN_CNT  IS '의견수';
COMMENT ON COLUMN BBS_ITEM.RCMD_CNT  IS '추천수';
COMMENT ON COLUMN BBS_ITEM.READ_CNT  IS '조회수';
COMMENT ON COLUMN BBS_ITEM.CSTM_FIELD1  IS '커스텀필드1';
COMMENT ON COLUMN BBS_ITEM.CSTM_FIELD2  IS '커스텀필드2';
COMMENT ON COLUMN BBS_ITEM.CSTM_FIELD3  IS '커스텀필드3';
COMMENT ON COLUMN BBS_ITEM.CSTM_DATE1  IS '커스텀일자1';
COMMENT ON COLUMN BBS_ITEM.CSTM_DATE2  IS '커스텀일자2';

ALTER TABLE BBS_ITEM ADD CONSTRAINT PK_BBSITEM_ITEMID PRIMARY KEY(ITEM_ID);
--ALTER TABLE USERS ADD CONSTRAINT FK_USERS FOREIGN KEY(USERNO);